name: Add issues to project workflow
on:
  workflow_call:

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/xmtp-labs/projects/24
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, enhancement
          label-operator: OR
